server:
  port: 8888
  #  日志配置
  logging:
    file: E:\\logs
    pattern:
      # 在控制台输出的日志的格式
      # %d表示日期时间，
      # %thread表示线程名，
      # %-5level：级别从左显示5个字符宽度
      # %logger{50} 表示logger名字最长50个字符，否则按照句点分割。
      # %msg：日志消息，
      # %n是换行符
      console: '%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{50} - %msg%n'
      # 指定文件中日志输出的格式
      file: '%d{yyyy-MM-dd HH:mm:ss} === [%thread]=== %-5level %logger{50} - %msg%n'
    # 配置日志级别
    # Logging level can be one of one of TRACE, DEBUG, INFO, WARN, ERROR, FATAL, OFF,
    # and TRACE < DEBUG < INFO < WARN < ERROR < FATAL < OFF
    level:
      root: INFO
      com.alipay: DEBUG
      org.springframework.web: DEBUG
